"""add share_id column

Revision ID: 08bdad82c044
Revises: 68176b6484d2
Create Date: 2025-10-28 00:33:45.081930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bdad82c044'
down_revision = '68176b6484d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('note_share_id_key'), type_='unique')
        batch_op.drop_column('share_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('note_share_id_key'), ['share_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
