"""migration

Revision ID: 08fac5b68731
Revises: 0456ab725649
Create Date: 2025-10-27 21:23:17.521277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fac5b68731'
down_revision = '0456ab725649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('answer_question_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('answer_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('explanation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('explanation_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'note', ['note_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('file_url',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('thumbnail_url',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_column('profile_image')
        batch_op.drop_column('bio')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('question_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('saved_note', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('saved_note_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('saved_note_note_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'note', ['note_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('viewed_note', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('viewed_note_note_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('viewed_note_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'note', ['note_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewed_note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('viewed_note_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('viewed_note_note_id_fkey'), 'note', ['note_id'], ['id'])

    with op.batch_alter_table('saved_note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('saved_note_note_id_fkey'), 'note', ['note_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('saved_note_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('question_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.alter_column('thumbnail_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('file_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('explanation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('explanation_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('note_id')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('answer_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('answer_question_id_fkey'), 'question', ['question_id'], ['id'])
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
