"""Baseline without share_id

Revision ID: 249751338d7b
Revises: 
Create Date: 2025-10-29 20:21:39.515489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249751338d7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('note_share_id_key'), type_='unique')
        batch_op.drop_column('share_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('note_share_id_key'), ['share_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
