"""Add share_id column

Revision ID: 68176b6484d2
Revises: bd310fa0ab43
Create Date: 2025-10-28 00:17:52.618056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68176b6484d2'
down_revision = 'bd310fa0ab43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('share_id',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('share_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###
