"""Add share_id

Revision ID: 89178973b375
Revises: 249751338d7b
Create Date: 2025-10-29 20:34:49.283281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89178973b375'
down_revision = '249751338d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['share_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('share_id')

    # ### end Alembic commands ###
