"""Add share_id to notes

Revision ID: bd310fa0ab43
Revises: 08fac5b68731
Create Date: 2025-10-27 23:56:57.938819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd310fa0ab43'
down_revision = '08fac5b68731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_id', sa.String(length=400), nullable=True))
        batch_op.create_unique_constraint(None, ['share_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('share_id')

    # ### end Alembic commands ###
